services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # 컨테이너 시작 시 발생하는 bcrypt 라이브러리의 invalid ELF 에러 방지를 위해 /app/node_modules로 변경하여 컨테이너의 node_modules를 사용하도록 변경
      # - /usr/src/app/node_modules 
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=smart-employee-management
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart-employee-management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 